[project]
name = "smart-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "python-docx>=1.1.0",
    "whoosh>=2.7.4",
]
